name: Android Release

on:
  push:
    branches: [ "testapk" ]
  pull_request:
    branches: [ "testapk" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.4.3"  # Specify Flutter version with Dart >= 3.4.3
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
